import emoji

PLAYER_ID = 0

STARTING_CASH_AMOUNT = 1500
MAX_PLAYERS = 4

NUM_PROPERTIES = 40

SPACE = " "
PLAYER_SYMBOL_STRING_LENGTH = 9
PLAYER_WIDE_SYMBOL_STRING_LENGTH = 15

BANK = "-1"

MEDITERRANEAN_AVENUE = "Mediterranean Avenue"
BALTIC_AVENUE = "Baltic Avenue"
READING_RAILROAD = "Reading Railroad"
ORIENTAL_AVENUE = "Oriental Avenue"
VERMONT_AVENUE = "Vermont Avenue"
CONNECTICUT_AVENUE = "Connecticut Avenue"
ST_CHARLES_PLACE = "St. Charles Place"
ELECTRIC_COMPANY = "Electric Company"
STATES_AVENUE = "States Avenue"
VIRGINIA_AVENUE = "Virginia Avenue"
PENNSYLVANIA_RAILROAD = "Pennsylvania Railroad"
ST_JAMES_PLACE = "St. James Place"
TENNESSEE_AVENUE = "Tennessee Avenue"
NEW_YORK_AVENUE = "New York Avenue"
KENTUCKY_AVENUE = "Kentucky Avenue"
INDIANA_AVENUE = "Indiana Avenue"
ILLINOIS_AVENUE = "Illinois Avenue"
B_AND_O_RAILROAD = "B&O Railroad"
ATLANTIC_AVENUE = "Atlantic Avenue"
VENTNOR_AVENUE = "Ventnor Avenue"
WATER_WORKS = "Water Works"
MARVIN_GARDENS = "Marvin Gardens"
PACIFIC_AVENUE = "Pacific Avenue"
NORTH_CAROLINA_AVENUE = "North Carolina Avenue"
PENNSYLVANIA_AVENUE = "Pennsylvania Avenue"
SHORT_LINE = "Short Line"
PARK_PLACE = "Park Place"
BOARDWALK = "Boardwalk"

GO_TO_JAIL_ID = 30
JUST_VISITING_ID = 10
JAIL_ID = 40
INCOME_TAX_ID = 4
LUXURY_TAX_ID = 38

PROPERTY_TO_INDEX_MAP = {
    MEDITERRANEAN_AVENUE: "01",
    BALTIC_AVENUE: "03",
    # READING_RAILROAD: "05",
    ORIENTAL_AVENUE: "06",
    VERMONT_AVENUE: "08",
    CONNECTICUT_AVENUE: "09",
    ST_CHARLES_PLACE: "11",
    # ELECTRIC_COMPANY: "12",
    STATES_AVENUE: "13",
    VIRGINIA_AVENUE: "14",
    # PENNSYLVANIA_RAILROAD: "15",
    ST_JAMES_PLACE: "16",
    TENNESSEE_AVENUE: "18",
    NEW_YORK_AVENUE: "19",
    KENTUCKY_AVENUE: "21",
    INDIANA_AVENUE: "23",
    ILLINOIS_AVENUE: "24",
    # B_AND_O_RAILROAD: "25",
    ATLANTIC_AVENUE: "26",
    VENTNOR_AVENUE: "27",
    # WATER_WORKS: "28",
    MARVIN_GARDENS: "29",
    PACIFIC_AVENUE: "31",
    NORTH_CAROLINA_AVENUE: "32",
    PENNSYLVANIA_AVENUE: "34",
    # SHORT_LINE: "35",
    PARK_PLACE: "37",
    BOARDWALK: "39",
}

INDEX_TO_PROPERTY_MAP = {
    PROPERTY_TO_INDEX_MAP[k]: k for k in PROPERTY_TO_INDEX_MAP
}

CAN_BUILD = {k for k in INDEX_TO_PROPERTY_MAP}

HOUSE = emoji.emojize(":house:")
HOTEL = emoji.emojize(":hotel:")

GO_AMT = 200
JAIL_AMT = 50
TAX_AMT = 200

JAIL_MAX_TURNS = 3

MAX_HOUSES = 5

# --------- USER COMMANDS ----------


YES_COMMAND = ["y", "yes"]
BUY_COMMANDS = ["b", "buy"]
INVENTORY_COMMANDS = ["i", "inv", "inventory"]
FINISH_COMMANDS = ["f", "fin", "finish"]

# --------- COLORS ----------
# https://stackoverflow.com/questions/39473297/how-do-i-print-colored-output-with-python-3

CEND = '\33[0m'
CBOLD = '\33[1m'
CITALIC = '\33[3m'
CURL = '\33[4m'
CBLINK = '\33[5m'
CBLINK2 = '\33[6m'
CSELECTED = '\33[7m'

CBLACK = '\33[30m'
CRED = '\33[31m'
CGREEN = '\33[32m'
CYELLOW = '\33[33m'
CBLUE = '\33[34m'
CVIOLET = '\33[35m'
CBEIGE = '\33[36m'
CWHITE = '\33[37m'

CBLACKBG = '\33[40m'
CREDBG = '\33[41m'
CGREENBG = '\33[42m'
CYELLOWBG = '\33[43m'
CBLUEBG = '\33[44m'
CVIOLETBG = '\33[45m'
CBEIGEBG = '\33[46m'
CWHITEBG = '\33[47m'

CGREY = '\33[90m'
CRED2 = '\33[91m'
CGREEN2 = '\33[92m'
CYELLOW2 = '\33[93m'
CBLUE2 = '\33[94m'
CVIOLET2 = '\33[95m'
CBEIGE2 = '\33[96m'
CWHITE2 = '\33[97m'

CGREYBG = '\33[100m'
CREDBG2 = '\33[101m'
CGREENBG2 = '\33[102m'
CYELLOWBG2 = '\33[103m'
CBLUEBG2 = '\33[104m'
CVIOLETBG2 = '\33[105m'
CBEIGEBG2 = '\33[106m'
CWHITEBG2 = '\33[107m'

GRY_HDR = CGREYBG + SPACE * PLAYER_WIDE_SYMBOL_STRING_LENGTH + CEND
RED_HDR = CREDBG2 + SPACE * PLAYER_WIDE_SYMBOL_STRING_LENGTH + CEND
GRE_HDR = CGREENBG2 + SPACE * PLAYER_SYMBOL_STRING_LENGTH + CEND
YEL_HDR = CYELLOWBG2 + SPACE * PLAYER_SYMBOL_STRING_LENGTH + CEND
BLU_HDR = CBLUEBG2 + SPACE * PLAYER_WIDE_SYMBOL_STRING_LENGTH + CEND
VIO_HDR = CVIOLETBG2 + SPACE * PLAYER_WIDE_SYMBOL_STRING_LENGTH + CEND
BEI_HDR = CBEIGEBG2 + SPACE * PLAYER_SYMBOL_STRING_LENGTH + CEND
WHI_HDR = CWHITEBG2 + SPACE * PLAYER_SYMBOL_STRING_LENGTH + CEND
